classDiagram
    Engine <|-- MultiEngine
    Engine <|-- SoloEngine
    Engine o-- Setting
    Engine o-- Lobby
    Engine o-- IInputHandler
    Engine o-- INetwork
    Engine o-- IRenderer
    IInputHandler <|-- LinuxInput
    IInputHandler <|-- WindowInput
    INetwork <|-- LinuxNetwork
    INetwork <|-- WindowNetwork
    IRenderer <|-- WindowMultiRenderer
    IRenderer <|-- WindowRenderer
    IRenderer <|-- LinuxMultiRenderer 
    IRenderer <|-- LinuxRenderer
    WindowMultiRenderer o-- Setting 
    WindowRenderer o-- Setting 
    LinuxMultiRenderer o-- Setting 
    LinuxRenderer o-- Setting 
    class Engine {
        #Setting* setting
        #IInputHandler* input_handler
        #IRenderer* renderer
        #INetwork* network
        #Lobby* lobby
        +Engine(Setting* setting, IInputHandler* input_handler, IRenderer* renderer, INetwork* network, Lobby* lobby)
        +run(bool is_server)*
        +stop()*
        +finish() int*
        +~Engine()
    }
    class MultiEngine{
      +MultiEngine(Setting* setting, IInputHandler* input_handler, IRenderer* renderer, INetwork* network, Lobby* lobby)
      +run(bool is_server)
      +stop()
      +finish() int
      +~MultiEngine()
    }
    class SoloEngine{
      +SoloEngine(Setting* setting, IInputHandler* input_handler, IRenderer* renderer)
      +run(bool is_server)
      +stop()
      +finish() int
      +~SoloEngine()
    }
    class Setting{
        +uint8_t color_theme
        +bool shadow_on;
        +std::string nick_name;
        +std::string server_ip_address;
        +std::string server_port;
        +set(const std::string& key, const std::string& value)
    }
    class Lobby{
        -std::unordered_map&lt;std::string, std::string&gt; server_ip_address
        -std::unordered_map&lt;std::string, std::string&gt; client_ip_address
        -char selected_server_ip_address[16]
        -char my_id[9]
        -ILobbyNetwork* lobby_network
        -ILobbyRenderer* lobby_renderer
        -ILobbyInputHandler* lobby_input_handler
        -find_broadcast_ip(char* broadcast_ip)
        -open_room() bool
        -enter_room() bool
        +Lobby(ILobbyNetwork* lobby_network, ILobbyRenderer* lobby_renderer, ILobbyInputHandler* lobby_input_handler)
        +start() bool
        +finish()
        +get_client_ip_address(std::string key) const char#42;
        +get_client_ids_ips() std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt;
        +get_ids(bool is_server) std::unordered_map<std::string, std::string>
        +get_server_ip_address() const char#42;
        +get_my_id() const char#42;
    }
    class IInputHandler{
        <<interface>>
        +scan() int*
        +~IInputHandler()*
    }
    class INetwork{
        <<interface>>
        +send_udp(const Board& board, const Tetromino& tetromino, int deleted_line, int is_game_over, int is_win, const char* another_user_ip, const char* my_id)*
        +send_multi_udp(const Board& board, const Tetromino& tetromino, int deleted_line, int is_game_over, int is_win, const char* my_id, std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt; ids_ips)*
        +send_relay_udp(const Packet& packet, std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt; ids_ips)*
        +recv_udp(Packet& recv_pkt) bool*
        +~INetwork()*
    }
    class IRenderer{
        <<interface>>
        +render_background()*
        +render_board(const Board& board, const Tetromino& tetromino)*
        +render_timer(int sec)*
        +render_next_block(const int* tetrominoArray)*
        +render_hold(const Tetromino& tetromino)*
        +render_score(int score)*
        +render_other_board(Packet& pkt)*
        +render_game_over()*
        +render_other_game_over(Packet& pkt)*
        +render_win()*
        +render_other_win(Packet& pkt)*
        +render_level(int level)*
        +render_clear()*
        +~IRenderer()*
    }
    class LinuxInput{
        -bool inited
        -termios old
        -enable_noncanonical_noecho()
        -restore()
        -_kbhit() int
        +scan() int
        +get_line() std::string
    }
    class WindowInput{
        +scan() int
        +get_line() std::string
        +~WindowInput()
    }
    class LinuxNetwork{
        -int client_sock
        -int server_sock
        -int epfd
        -epoll_event events[MAX_EVENTS]
        -write_32b(uint8_t*& p, int32_t v)
        -write_bytes(uint8_t*& p, const void* data, size_t size)
        -serialize(uint8_t* buf, const Packet& pkt)
        -read_32b(const uint8_t*& p) int32_t
        -read_bytes(const uint8_t*& p, void* dst, size_t size)
        -deserialize(const uint8_t* buf, Packet& pkt)
        +LinuxNetwork()
        +send_udp(const Board& board, const Tetromino& tetromino, int deleted_line, int is_game_over, int is_win, const char* another_user_ip, const char* my_id)
        +send_multi_udp(const Board& board, const Tetromino& tetromino, int deleted_line, int is_game_over, int is_win, const char* my_id, std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt; ids_ips)
        +send_relay_udp(const Packet& packet, std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt; ids_ips)
        +recv_udp(Packet& recv_pkt) bool
        +~LinuxNetwork()
    }
    class WindowNetwork{     
        -SOCKET client_sock
        -SOCKET server_sock
        -SOCKADDR_IN server_addr
        -SOCKADDR_IN client_addr
        -write_32b(uint8_t*& p, int32_t v)
        -write_bytes(uint8_t*& p, const void* data, size_t size)
        -serialize(uint8_t* buf, const Packet& pkt)
        -read_32b(const uint8_t*& p) int32_t
        -read_bytes(const uint8_t*& p, void* dst, size_t size)
        -deserialize(const uint8_t* buf, Packet& pkt)
        +WindowNetwork()
        +send_udp(const Board& board, const Tetromino& tetromino, int deleted_line, int is_game_over, int is_win, const char* another_user_ip, const char* my_id)
        +send_multi_udp(const Board& board, const Tetromino& tetromino, int deleted_line, int is_game_over, int is_win, const char* my_id, std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt; ids_ips)
        +send_relay_udp(const Packet& packet, std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt; ids_ips)
        +recv_udp(Packet& recv_pkt) bool
        +~WindowNetwork()
    }
    class WindowMultiRenderer{
        -Setting* setting
        -IPlatformRenderer* platform_renderer
        -ColorPicker color_picker
        -TextRenderer text_renderer
        -BoxRenderer box_renderer
        -BlockRenderer block_renderer
        -ShadowMaker shadow_maker
        -std::unordered_map<std::string, int> other_land_index_map
        -std::pair<int, int> other_render_loc_array[3]
        -int other_render_index
        -other_render_loc_get_or_set(std::string id) std::pair<int, int>
        +WindowMultiRenderer(Setting*, IPlatformRenderer*, ColorPicker, TextRenderer, BoxRenderer, BlockRenderer, ShadowMaker)
        +render_background()
        +render_board(const Board& board, const Tetromino& tetromino)
        +render_timer(int sec)
        +render_next_block(const int* tetrominoArray)
        +render_hold(const Tetromino& tetromino)
        +render_score(int score)
        +render_other_board(Packet& pkt)
        +render_game_over()
        +render_other_game_over(Packet& pkt)
        +render_win()
        +render_other_win(Packet& pkt)
        +render_level(int level)
        +render_clear()
        +~WindowMultiRenderer()*
    }
    class WindowRenderer{
        -Setting* setting
        -IPlatformRenderer* platform_renderer
        -ColorPicker color_picker
        -TextRenderer text_renderer
        -BoxRenderer box_renderer
        -BlockRenderer block_renderer
        -ShadowMaker shadow_maker
        +WindowRenderer(Setting*, IPlatformRenderer*, ColorPicker, TextRenderer, BoxRenderer, BlockRenderer, ShadowMaker)
        +WindowRenderer()
        +render_background()
        +render_board(const Board& board, const Tetromino& tetromino)
        +render_timer(int sec)
        +render_next_block(const int* tetrominoArray)
        +render_hold(const Tetromino& tetromino)
        +render_score(int score)
        +render_other_board(Packet& pkt)
        +render_game_over()
        +render_other_game_over(Packet& pkt)
        +render_win()
        +render_other_win(Packet& pkt)
        +render_level(int level)
        +render_clear()
        +~WindowRenderer()*
    }
    class LinuxMultiRenderer{
        -Setting* setting
        -IPlatformRenderer* platform_renderer
        -ColorPicker color_picker
        -TextRenderer text_renderer
        -BoxRenderer box_renderer
        -BlockRenderer block_renderer
        -ShadowMaker shadow_maker
        -std::unordered_map<std::string, int> other_land_index_map
        -std::pair<int, int> other_render_loc_array[3]
        -int other_render_index
        -other_render_loc_get_or_set(std::string id) std::pair<int, int>
        +LinuxMultiRenderer(Setting*, IPlatformRenderer*, ColorPicker, TextRenderer, BoxRenderer, BlockRenderer, ShadowMaker)
        +render_background()
        +render_board(const Board& board, const Tetromino& tetromino)
        +render_timer(int sec)
        +render_next_block(const int* tetrominoArray)
        +render_hold(const Tetromino& tetromino)
        +render_score(int score)
        +render_other_board(Packet& pkt)
        +render_game_over()
        +render_other_game_over(Packet& pkt)
        +render_win()
        +render_other_win(Packet& pkt)
        +render_level(int level)
        +render_clear()
        +~LinuxMultiRenderer()*
    }
    class LinuxRenderer{
        -Setting* setting
        -IPlatformRenderer* platform_renderer
        -ColorPicker color_picker
        -TextRenderer text_renderer
        -BoxRenderer box_renderer
        -BlockRenderer block_renderer
        -ShadowMaker shadow_maker
        +LinuxRenderer(Setting*, IPlatformRenderer*, ColorPicker, TextRenderer, BoxRenderer, BlockRenderer, ShadowMaker)
        +LinuxRenderer()
        +render_background()
        +render_board(const Board& board, const Tetromino& tetromino)
        +render_timer(int sec)
        +render_next_block(const int* tetrominoArray)
        +render_hold(const Tetromino& tetromino)
        +render_score(int score)
        +render_other_board(Packet& pkt)
        +render_game_over()
        +render_other_game_over(Packet& pkt)
        +render_win()
        +render_other_win(Packet& pkt)
        +render_level(int level)
        +render_clear()
        +~LinuxRenderer()
    }